cat("ERBioR bilingual Shiny smoke test\n")
stopifnot(as.character(packageVersion("ERBioR")) == "0.9.0")
stopifnot(exists("erbio_run_app", where = asNamespace("ERBioR"), inherits = FALSE))
ERBioR::erbio_set_language("es")
stopifnot(ERBioR::erbio_get_language() == "es")
ERBioR::erbio_set_language("en")
stopifnot(ERBioR::erbio_get_language() == "en")
v <- ERBioR::erbio_validate_translation_registry()
stopifnot(isTRUE(v$valid), v$n_items == 1008L)
r <- rep("Si", 48); r[28] <- "No"
es <- ERBioR::erbio_score_questionnaire("general", r, language = "es")
en <- ERBioR::erbio_score_questionnaire("general", r, language = "en")
stopifnot(identical(es$compliance_percent, en$compliance_percent))
stopifnot(identical(es$failed_controls$item_id, en$failed_controls$item_id))
cat("BILINGUAL CORE SMOKE TEST PASSED\n")
cat("Launch with: ERBioR::erbio_run_app()\n")
